<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Event;
use App\Models\Location;
use App\Models\Department;
use App\Models\User;
use Carbon\Carbon;

class EventsTableSeeder extends Seeder
{
    public function run()
    {
        // Create or reference departments
        $departments = [
            'Khoa CNTT' => Department::firstOrCreate(['name' => 'Khoa CNTT'], ['id' => 1]),
            'Ban CSVC và ĐT' => Department::firstOrCreate(['name' => 'Ban CSVC và ĐT']),
            'VPĐU' => Department::firstOrCreate(['name' => 'VPĐU']),
            'Tổ công tác' => Department::firstOrCreate(['name' => 'Tổ công tác']),
            'Ban KHCN' => Department::firstOrCreate(['name' => 'Ban KHCN']),
            'TT QHCC&HTSV' => Department::firstOrCreate(['name' => 'TT QHCC&HTSV']),
            'NXB Học viện NN' => Department::firstOrCreate(['name' => 'NXB Học viện NN']),
            'Ban TCKT' => Department::firstOrCreate(['name' => 'Ban TCKT']),
            'Đoàn TN' => Department::firstOrCreate(['name' => 'Đoàn TN']),
            'Khoa TNMT' => Department::firstOrCreate(['name' => 'Khoa TNMT']),
            'Khoa Cơ Điện' => Department::firstOrCreate(['name' => 'Khoa Cơ Điện']),
            'Ban ĐBCL và Pháp chế' => Department::firstOrCreate(['name' => 'Ban ĐBCL và Pháp chế']),
            'Ban HTQT' => Department::firstOrCreate(['name' => 'Ban HTQT']),
            'TT GDTCTT' => Department::firstOrCreate(['name' => 'TT GDTCTT']),
            'TT NCXS&ĐMST' => Department::firstOrCreate(['name' => 'TT NCXS&ĐMST']),
            'Ban QLĐT' => Department::firstOrCreate(['name' => 'Ban QLĐT']),
            'Ban CTCT&CTSV' => Department::firstOrCreate(['name' => 'Ban CTCT&CTSV']),
            'VPHV' => Department::firstOrCreate(['name' => 'VPHV']),
            'TT CUNNL' => Department::firstOrCreate(['name' => 'TT CUNNL']),
            'Viện AMI' => Department::firstOrCreate(['name' => 'Viện AMI']),
            'Khoa KT&QL' => Department::firstOrCreate(['name' => 'Khoa KT&QL']),
            'Khoa DL&NN' => Department::firstOrCreate(['name' => 'Khoa DL&NN']),
            'Khoa KT&QTKD' => Department::firstOrCreate(['name' => 'Khoa KT&QTKD']),
            'Khoa Thủy sản' => Department::firstOrCreate(['name' => 'Khoa Thủy sản']),
            'TT Tin học' => Department::firstOrCreate(['name' => 'TT Tin học']),
        ];

        // Create or reference locations
        $locations = [
            'Phòng họp Bằng Lăng' => Location::firstOrCreate(['name' => 'Phòng họp Bằng Lăng']),
            'Hội trường 4A, Trụ sở Thàng ủy, Số 219 Trần Phú, Hà Đông, Hà Nội' => Location::firstOrCreate(['name' => 'Hội trường 4A, Trụ sở Thàng ủy, Số 219 Trần Phú, Hà Đông, Hà Nội']),
            'Phòng họp Giáng Hương' => Location::firstOrCreate(['name' => 'Phòng họp Giáng Hương']),
            'Hội trường Trung Tâm' => Location::firstOrCreate(['name' => 'Hội trường Trung Tâm']),
            'Nhà xuất bản Học viện NN' => Location::firstOrCreate(['name' => 'Nhà xuất bản Học viện NN']),
            'Giảng trường trung tâm' => Location::firstOrCreate(['name' => 'Giảng trường trung tâm']),
            'Bộ Khoa học và Công nghệ' => Location::firstOrCreate(['name' => 'Bộ Khoa học và Công nghệ']),
            'Công trường thi công' => Location::firstOrCreate(['name' => 'Công trường thi công']),
            'Trường Đại học Cần Thơ' => Location::firstOrCreate(['name' => 'Trường Đại học Cần Thơ']),
            'Trụ sở HĐND-UBND xã Thạch Thất' => Location::firstOrCreate(['name' => 'Trụ sở HĐND-UBND xã Thạch Thất']),
            'Hội trường Nguyệt Quế' => Location::firstOrCreate(['name' => 'Hội trường Nguyệt Quế']),
            'Phòng họp Hoa Sứ' => Location::firstOrCreate(['name' => 'Phòng họp Hoa Sứ']),
            'KS JW Marirott' => Location::firstOrCreate(['name' => 'KS JW Marirott']),
            'Phòng họp Anh Đào' => Location::firstOrCreate(['name' => 'Phòng họp Anh Đào']),
            'Phòng Tiếp dân (P123 - Tòa nhà Trung tâm)' => Location::firstOrCreate(['name' => 'Phòng Tiếp dân (P123 - Tòa nhà Trung tâm)']),
            'Phòng 405, tòa nhà Bùi Huy Đáp' => Location::firstOrCreate(['name' => 'Phòng 405, tòa nhà Bùi Huy Đáp']),
            'Khoa Du lịch và Ngoại ngữ' => Location::firstOrCreate(['name' => 'Khoa Du lịch và Ngoại ngữ']),
        ];

        // Reference users
        $chanhvp = User::where('user_name', 'nguyenthilan')->firstOrFail(); // Chief of Office

        // Events from the schedule
        $events = [
            [
                'title' => 'Họp Hội đồng thanh lý tài sản',
                'description' => 'Thành viên Hội đồng theo QĐ của GĐHV',
                'start_time' => Carbon::create(2025, 7, 7, 9, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 7, 11, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Công Tiệp',
                'participants' => 'Thành viên Hội đồng theo QĐ của GĐHV',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Bằng Lăng'],
                'preparers' => ['Ban CSVC và ĐT'],
            ],
            [
                'title' => 'Tham dự Hội nghị thực hiện quy trình nhân sự lần đầu tham gia cấp ủy ĐBK nhiệm kỳ 2025 - 2030',
                'description' => 'Xe đón thầy/cô tại sảnh Nhà Trung tâm lúc 13h30',
                'start_time' => Carbon::create(2025, 7, 7, 14, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 7, 16, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Thường trực Đảng ủy Khối',
                'participants' => 'Nguyễn Thị Lan, Vũ Ngọc Huyên, Phạm Văn Cường',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Hội trường 4A, Trụ sở Thàng ủy, Số 219 Trần Phú, Hà Đông, Hà Nội'],
                'preparers' => ['VPĐU'],
            ],
            [
                'title' => 'Họp chuẩn bị làm việc với Bộ KHCN về đề án TT ĐMST Nông nghiệp Quốc gia',
                'description' => 'Ban Giám đốc, Trưởng các đơn vị: KHCN, HTQT, TCKT, CSVC&ĐT, QLĐT, CTCT&CTSV, TCCB',
                'start_time' => Carbon::create(2025, 7, 7, 16, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 7, 17, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Ban Giám đốc, Trưởng các đơn vị: KHCN, HTQT, TCKT, CSVC&ĐT, QLĐT, CTCT&CTSV, TCCB',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Giáng Hương'],
                'preparers' => ['Tổ công tác'],
            ],
            [
                'title' => 'Hội nghị phổ biến thông tin tuyển sinh trình độ đại học, thạc sĩ, tiến sĩ, sinh viên nghiên cứu khoa học (Ca 3)',
                'description' => 'Cán bộ, viên chức, người lao động có mặt tại Hội trường trước 15 phút để phục vụ công tác điểm danh',
                'start_time' => Carbon::create(2025, 7, 8, 8, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 8, 10, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Ban Giám đốc (Nguyễn Công Tiệp), Cán bộ, viên chức, người lao động chưa tham dự ca 1 và ca 2',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Hội trường Trung Tâm'],
                'preparers' => ['TT QHCC&HTSV'],
            ],
            [
                'title' => 'Họp với các nhóm NCM Khoa Chăn nuôi, Thú y, Thuỷ sản và TNMT',
                'description' => 'Triển khai Cụm đề tài Phát triển vắc-xin và các CPSH trong chăn nuôi, thú y và thủy sản. Thành phần: BGĐ (Phạm Văn Cường), Ban KHCN (Trần Hiệp, Đinh Văn Dũng, Nguyễn Minh Hân), Ban TCKT (Trần Quang Trung), Ban CSVC (Nguyễn Văn Quân), Ban HTQT (Nguyễn Việt Long), Nhóm viết Cụm đề tài Vắc xin và CPSH, Các nhóm NC (trưởng nhóm, thư ký và 2 thành viên chủ chốt)',
                'start_time' => Carbon::create(2025, 7, 8, 10, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 8, 12, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Phạm Văn Cường, Trần Hiệp, Đinh Văn Dũng, Nguyễn Minh Hân, Trần Quang Trung, Nguyễn Văn Quân, Nguyễn Việt Long, Nhóm Vắc xin và CPSH (Phan, Hoa, Lâm), Nhóm VSV-Bệnh truyền nhiễm (Hữu Anh, Ngân, Giáp), Nhóm Dược lý (Hà, Chiên), Nhóm Kháng kháng sinh (Đức, Thu Hà), Nhóm Bệnh Thủy sản (Hoài, Mạnh, Vạn), Nhóm Dinh dưỡng (Thu, Tùng), Nhóm Giống (Hạnh, Vinh), Nhóm Thức ăn (Oánh, Hương, Lê, Ánh), Nhóm Quản lý tài nguyên (Công, Hữu Dương), Nhóm Công nghệ môi trường (Huy, Thu Hà), Nhóm Quản lý đất (Việt Hà, Thu Hà), Khoa TNMT (Đinh Hồng Duyên, Hoàng Hiệp), Khoa KT&QL (Nguyễn Hữu Nhuần, Linh), Khoa KT&QTKD (Trần Quang Trung), TT giống vật nuôi CLC (Hà)',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Giáng Hương'],
                'preparers' => ['Ban KHCN'],
            ],
            [
                'title' => 'Nghe báo cáo kết quả đề án sinh viên NCKH và kế hoạch triển khai đề án CLB sinh viên, đề án nối vòng tay lớn',
                'description' => 'Ban Giám đốc (Nguyễn Công Tiệp), TTQHCH&HTSV (Kim Hương), Ban CTCT&CTSV (Khoa), Ban KHCN (Trần Hiệp), TTNCXS&ĐMST (Minh), Bí thư và các Phó Bí thư Đoàn TN',
                'start_time' => Carbon::create(2025, 7, 9, 8, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 9, 10, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Nguyễn Công Tiệp, Kim Hương, Khoa, Trần Hiệp, Minh, Bí thư và các Phó Bí thư Đoàn TN',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Giáng Hương'],
                'preparers' => ['Ban KHCN', 'Đoàn TN'],
            ],
            [
                'title' => 'Làm việc với đơn vị đối tác về công tác xuất bản',
                'description' => 'Nhà xuất bản Học viện NN (Lê Anh, Tuấn Anh), Đơn vị đối tác',
                'start_time' => Carbon::create(2025, 7, 9, 8, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 9, 10, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Vũ Ngọc Huyên',
                'participants' => 'Lê Anh, Tuấn Anh, Đơn vị đối tác',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Nhà xuất bản Học viện NN'],
                'preparers' => ['NXB Học viện NN'],
            ],
            [
                'title' => 'Nghiệm thu gói thầu: Cải tạo cơ sở vật chất giảng đường trung tâm',
                'description' => 'Ban Tài chính & Kế toán (Lãnh đạo Ban, Huyền), Ban ĐBCL&PC (Ước), Trung tâm dịch vụ trường học (Hải, Kim), Ban CSVC&ĐT (Nam, chuyên viên PT), Tư vấn giám sát, Tư vấn quản lý dự án, Nhà thầu thi công',
                'start_time' => Carbon::create(2025, 7, 9, 9, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 9, 11, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Phạm Văn Cường',
                'participants' => 'Huyền, Ước, Hải, Kim, Nam, chuyên viên PT, Tư vấn giám sát, Tư vấn quản lý dự án, Nhà thầu thi công',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Giảng trường trung tâm'],
                'preparers' => ['Ban CSVC và ĐT'],
            ],
            [
                'title' => 'Họp đề xuất Danh mục các dự án đầu tư công giai đoạn 2026-2030',
                'description' => 'Ban Giám đốc, Thường trực Hội đồng Học viện (Viên, Liết, Thâu), Đảng ủy viên, Trưởng các đơn vị: Ban Tài chính Kế toán, Văn phòng Học viện, Ban Khoa học Công nghệ, Ban Quản lý Đào tạo, Ban Cơ sở vật chất và Đầu tư',
                'start_time' => Carbon::create(2025, 7, 9, 10, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 9, 11, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Viên, Liết, Thâu, Đảng ủy viên, Trưởng các đơn vị: Ban TCKT, VPHV, Ban KHCN, Ban QLĐT, Ban CSVC&ĐT',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Giáng Hương'],
                'preparers' => ['Ban CSVC và ĐT'],
            ],
            [
                'title' => 'Làm việc với Quỹ Phát triển KHCN Quốc gia về nhiệm vụ "Nghiên cứu công nghệ thiết kế, chế tạo dây chuyền thiết bị sơ chế bảo quản cà rốt"',
                'description' => 'Mã số: ĐTĐL.CN-89/21, do PGS.TS. Lê Minh Lư làm chủ nhiệm. Thành phần: Ban KHCN, Ban TCKT, Khoa Cơ điện, Chủ nhiệm và Thành viên tham gia thực hiện đề tài',
                'start_time' => Carbon::create(2025, 7, 9, 14, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 9, 17, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Phạm Văn Cường',
                'participants' => 'Lê Minh Lư, Ban KHCN, Ban TCKT, Khoa Cơ điện, Thành viên tham gia thực hiện đề tài',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Bộ Khoa học và Công nghệ'],
                'preparers' => ['Ban KHCN'],
            ],
            [
                'title' => 'Nghiệm thu gói thầu: Thi công xây lắp đường dây cấp nguồn TBA giống lúa',
                'description' => 'Ban Tài chính & Kế toán (Lãnh đạo Ban, Huyền), Ban ĐBCL và Pháp chế (Ước), Ban CSVC&ĐT (Nam và chuyên viên phụ trách), Tư vấn giám sát, Nhà thầu thi công',
                'start_time' => Carbon::create(2025, 7, 9, 15, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 9, 16, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Công Tiệp',
                'participants' => 'Huyền, Ước, Nam, chuyên viên phụ trách, Tư vấn giám sát, Nhà thầu thi công',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Công trường thi công'],
                'preparers' => ['Ban CSVC và ĐT'],
            ],
            [
                'title' => 'Tham gia tiếp xúc cử tri sau kỳ họp thứ Chín, Quốc hội khóa XV',
                'description' => 'Đại biểu Quốc hội Nguyễn Thị Lan, Tổ công tác',
                'start_time' => Carbon::create(2025, 7, 10, 8, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 10, 11, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Nguyễn Thị Lan, Tổ công tác',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Trụ sở HĐND-UBND xã Thạch Thất'],
                'preparers' => ['Tổ công tác'],
            ],
            [
                'title' => 'Họp tiến độ công trình ao sen',
                'description' => 'Ban CSVC&ĐT (Nam và cán bộ chuyên môn), tổ giám sát độc lập (Ước, Huân), VPHV (Huân, Thuần), TVQLDA, TVGS, nhà thầu thi công',
                'start_time' => Carbon::create(2025, 7, 10, 9, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 10, 11, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Công Tiệp',
                'participants' => 'Nam, Ước, Huân, Thuần, TVQLDA, TVGS, nhà thầu thi công',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Bằng Lăng'],
                'preparers' => ['Ban CSVC và ĐT'],
            ],
            [
                'title' => 'Trình bày phương án thiết kế sân tập Golf',
                'description' => 'HĐKH&ĐT (Viên), HĐHV (Xuân Cường), Ban CSVC&ĐT, Văn phòng Học viện, TT GDTCTT',
                'start_time' => Carbon::create(2025, 7, 10, 14, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 10, 15, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Vũ Ngọc Huyên',
                'participants' => 'Viên, Xuân Cường, Ban CSVC&ĐT, VPHV, TT GDTCTT',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Giáng Hương'],
                'preparers' => ['Ban CSVC và ĐT'],
            ],
            [
                'title' => 'Họp nghe báo cáo tiến độ quảng bá tuyển sinh năm 2025',
                'description' => 'Ban Giám đốc, HĐKH&ĐT (Viên), Trưởng các ban chức năng, Phó Trưởng một số ban (Tùng, Tự, Lan Hương), Trưởng các khoa, viện, trung tâm, công ty, Bí thư và Phó Bí thư Đoàn TN',
                'start_time' => Carbon::create(2025, 7, 10, 15, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 10, 17, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Ban Giám đốc, Viên, Tùng, Tự, Lan Hương, Trưởng các khoa, viện, trung tâm, công ty, Bí thư và Phó Bí thư Đoàn TN',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Hội trường Nguyệt Quế'],
                'preparers' => ['TT QHCC&HTSV'],
            ],
            [
                'title' => 'Hội thảo triển khai Khung năng lực số cho sinh viên',
                'description' => 'Kinh nghiệm quốc tế và thực tiễn Việt Nam. Thành phần: Ban Giám đốc (Phạm Văn Cường), Ban QLĐT (Tự, Quốc, Tuyết), Ban ĐBCL và PC, Lãnh đạo khoa và trợ lý đào tạo, Quản trị mạng',
                'start_time' => Carbon::create(2025, 7, 11, 8, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 11, 12, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Bộ Giáo dục và Đào tạo',
                'participants' => 'Phạm Văn Cường, Tự, Quốc, Tuyết, Ban ĐBCL và PC, Lãnh đạo khoa và trợ lý đào tạo, Quản trị mạng',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Hội trường Nguyệt Quế'],
                'preparers' => ['Ban QLĐT'],
            ],
            [
                'title' => 'Thảo luận hợp tác với thành phố Tottori Nhật Bản',
                'description' => 'Đoàn thành phố Tottori Nhật Bản, TT CUNNL, trung tâm dịch vụ VNUA IDS',
                'start_time' => Carbon::create(2025, 7, 11, 10, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 11, 12, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Vũ Ngọc Huyên',
                'participants' => 'Đoàn thành phố Tottori Nhật Bản, TT CUNNL, VNUA IDS',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Anh Đào'],
                'preparers' => ['TT CUNNL'],
            ],
            [
                'title' => 'Họp tiến độ kiểm định 8 CTĐT đại học năm 2025',
                'description' => 'Trưởng các khoa (Chăn nuôi, DL&NN, KT&QTKD, KT&QL, TN&MT, Thủy sản), Trưởng nhóm viết BCTĐG, Thư ký hội đồng TĐG, Cán bộ phụ trách minh chứng, TT Tin học (Dũng), Tổ ĐBCL',
                'start_time' => Carbon::create(2025, 7, 11, 14, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 11, 15, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Phạm Văn Cường',
                'participants' => 'Trưởng các khoa (Chăn nuôi, DL&NN, KT&QTKD, KT&QL, TN&MT, Thủy sản), Trưởng nhóm viết BCTĐG, Thư ký hội đồng TĐG, Cán bộ phụ trách minh chứng, Dũng, Tổ ĐBCL',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Hội trường Nguyệt Quế'],
                'preparers' => ['Ban ĐBCL và Pháp chế'],
            ],
            [
                'title' => 'Nghiệm thu đề tài KHCN cấp Học viện trọng điểm',
                'description' => 'Do TS. Nguyễn Đình Thi làm chủ nhiệm. Thành viên Hội đồng, Ban KHCN',
                'start_time' => Carbon::create(2025, 7, 11, 14, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 11, 16, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Vũ Ngọc Huyên',
                'participants' => 'Nguyễn Đình Thi, Thành viên Hội đồng, Ban KHCN',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Hoa Sứ'],
                'preparers' => ['Ban KHCN'],
            ],
            [
                'title' => 'Họp triển khai đề án sinh viên nghiên cứu khoa học VNUA năm 2025',
                'description' => 'Ban Giám đốc, Trưởng các khoa, Trưởng các nhóm nghiên cứu mạnh, tinh hoa, xuất sắc, Ban KHCN, Ban QLĐT, Ban CTCT&CTSV, TT QHCC&HTSV, TT NCXS&ĐMST, Trợ lý khoa học các khoa, Ban Bí thư Đoàn TN, Văn phòng Đoàn TN',
                'start_time' => Carbon::create(2025, 7, 11, 15, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 11, 17, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Ban Giám đốc, Trưởng các khoa, Trưởng các nhóm nghiên cứu, Ban KHCN, Ban QLĐT, Ban CTCT&CTSV, TT QHCC&HTSV, TT NCXS&ĐMST, Trợ lý khoa học, Ban Bí thư Đoàn TN, Văn phòng Đoàn TN',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Hội trường Nguyệt Quế'],
                'preparers' => ['Đoàn TN'],
            ],
            [
                'title' => 'Họp rút kinh nghiệm tổ chức thi trên hệ thống phần mềm VNUA-TEST năm học 2024-2025',
                'description' => 'Đại diện Ban chủ nhiệm khoa và Bộ môn phụ trách học phần, Trưởng học phần của 13 Học phần chung, Ban QLĐT, Ban CSVC&ĐT, TT Tin học, Bộ phận Quản trị mạng',
                'start_time' => Carbon::create(2025, 7, 11, 15, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 11, 17, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Phạm Văn Cường',
                'participants' => 'Ban chủ nhiệm khoa, Bộ môn phụ trách học phần, Trưởng học phần, Ban QLĐT, Ban CSVC&ĐT, TT Tin học, Bộ phận Quản trị mạng',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Giáng Hương'],
                'preparers' => ['Ban ĐBCL và Pháp chế'],
            ],
            [
                'title' => 'Lễ kỷ niệm 249 năm Quốc khánh Hoa Kỳ và 30 năm thiết lập quan hệ ngoại giao Hoa Kỳ - Việt Nam',
                'description' => 'GĐ Nguyễn Thị Lan, Lãnh đạo Ban HTQT',
                'start_time' => Carbon::create(2025, 7, 11, 18, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 11, 20, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Nguyễn Thị Lan, Ban HTQT',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['KS JW Marirott'],
                'preparers' => ['Ban HTQT'],
            ],
            [
                'title' => 'Làm việc với Hội Tự động hoá Việt Nam về kế hoạch hợp tác đào tạo và nghiên cứu khoa học',
                'description' => 'GS.TS. Trần Đức Viên, Ban Giám đốc (Vũ Ngọc Huyên), Ban QLĐT (Hải), Ban KHCN (Trần Hiệp), Khoa Cơ Điện (Trường, Hiên, Học)',
                'start_time' => Carbon::create(2025, 7, 12, 15, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 12, 17, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Vũ Ngọc Huyên',
                'participants' => 'Trần Đức Viên, Vũ Ngọc Huyên, Hải, Trần Hiệp, Trường, Hiên, Học',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Giáng Hương'],
                'preparers' => ['Khoa Cơ Điện'],
            ],
            [
                'title' => 'Tiếp cán bộ, viên chức, người lao động và người học',
                'description' => 'Ban Thanh tra, Ban Thanh tra nhân dân',
                'start_time' => Carbon::create(2025, 7, 15, 8, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 15, 11, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Ban Thanh tra, Ban Thanh tra nhân dân',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng Tiếp dân (P123 - Tòa nhà Trung tâm)'],
                'preparers' => ['VPHV'],
            ],
            [
                'title' => 'Tiếp đoàn SFSI về dự án Cooperative Innovation Ecosystem Development',
                'description' => 'Thảo luận kế hoạch triển khai dự án. Thành phần: Ban HTQT (Nguyễn Việt Long, Dương Thị Minh Phượng), Ban KHCN (Trần Hiệp), Khoa KT&QL (Nguyễn Hữu Nhuần, Trần Thế Cường), Viện AMI (Ngô Sỹ Đạt), Nhóm NCM HTX (Trần Quang Trung), TT NCXS ĐMST (Trần Đức Minh), SFSI (Michael Murphy, Michael Barry, Aoife Roche, Hoàng Văn Tú)',
                'start_time' => Carbon::create(2025, 7, 14, 14, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 14, 16, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Trần Đức Viên',
                'participants' => 'Nguyễn Việt Long, Dương Thị Minh Phượng, Trần Hiệp, Nguyễn Hữu Nhuần, Trần Thế Cường, Ngô Sỹ Đạt, Trần Quang Trung, Trần Đức Minh, Michael Murphy, Michael Barry, Aoife Roche, Hoàng Văn Tú',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Hoa Sứ'],
                'preparers' => ['Ban HTQT'],
            ],
                        [
                'title' => 'Họp Hội đồng thanh lý tài sản',
                'description' => 'Thành viên Hội đồng theo QĐ của GĐHV',
                'start_time' => Carbon::create(2025, 7, 14, 9, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 14, 11, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Công Tiệp',
                'participants' => 'Thành viên Hội đồng theo QĐ của GĐHV',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Bằng Lăng'],
                'preparers' => ['Ban CSVC và ĐT'],
            ],
            [
                'title' => 'Tham dự Hội nghị thực hiện quy trình nhân sự lần đầu tham gia cấp ủy ĐBK nhiệm kỳ 2025 - 2030',
                'description' => 'Xe đón thầy/cô tại sảnh Nhà Trung tâm lúc 13h30',
                'start_time' => Carbon::create(2025, 7, 14, 14, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 14, 16, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Thường trực Đảng ủy Khối',
                'participants' => 'Nguyễn Thị Lan, Vũ Ngọc Huyên, Phạm Văn Cường',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Hội trường 4A, Trụ sở Thàng ủy, Số 219 Trần Phú, Hà Đông, Hà Nội'],
                'preparers' => ['VPĐU'],
            ],
            [
                'title' => 'Họp chuẩn bị làm việc với Bộ KHCN về đề án TT ĐMST Nông nghiệp Quốc gia',
                'description' => 'Ban Giám đốc, Trưởng các đơn vị: KHCN, HTQT, TCKT, CSVC&ĐT, QLĐT, CTCT&CTSV, TCCB',
                'start_time' => Carbon::create(2025, 7, 14, 16, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 14, 17, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Ban Giám đốc, Trưởng các đơn vị: KHCN, HTQT, TCKT, CSVC&ĐT, QLĐT, CTCT&CTSV, TCCB',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Giáng Hương'],
                'preparers' => ['Tổ công tác'],
            ],
            [
                'title' => 'Hội nghị phổ biến thông tin tuyển sinh trình độ đại học, thạc sĩ, tiến sĩ, sinh viên nghiên cứu khoa học (Ca 3)',
                'description' => 'Cán bộ, viên chức, người lao động có mặt tại Hội trường trước 15 phút để phục vụ công tác điểm danh',
                'start_time' => Carbon::create(2025, 7, 15, 8, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 15, 10, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Ban Giám đốc (Nguyễn Công Tiệp), Cán bộ, viên chức, người lao động chưa tham dự ca 1 và ca 2',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Hội trường Trung Tâm'],
                'preparers' => ['TT QHCC&HTSV'],
            ],
            [
                'title' => 'Họp với các nhóm NCM Khoa Chăn nuôi, Thú y, Thuỷ sản và TNMT',
                'description' => 'Triển khai Cụm đề tài Phát triển vắc-xin và các CPSH trong chăn nuôi, thú y và thủy sản. Thành phần: BGĐ (Phạm Văn Cường), Ban KHCN (Trần Hiệp, Đinh Văn Dũng, Nguyễn Minh Hân), Ban TCKT (Trần Quang Trung), Ban CSVC (Nguyễn Văn Quân), Ban HTQT (Nguyễn Việt Long), Nhóm viết Cụm đề tài Vắc xin và CPSH, Các nhóm NC (trưởng nhóm, thư ký và 2 thành viên chủ chốt)',
                'start_time' => Carbon::create(2025, 7, 15, 10, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 15, 12, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Phạm Văn Cường, Trần Hiệp, Đinh Văn Dũng, Nguyễn Minh Hân, Trần Quang Trung, Nguyễn Văn Quân, Nguyễn Việt Long, Nhóm Vắc xin và CPSH (Phan, Hoa, Lâm), Nhóm VSV-Bệnh truyền nhiễm (Hữu Anh, Ngân, Giáp), Nhóm Dược lý (Hà, Chiên), Nhóm Kháng kháng sinh (Đức, Thu Hà), Nhóm Bệnh Thủy sản (Hoài, Mạnh, Vạn), Nhóm Dinh dưỡng (Thu, Tùng), Nhóm Giống (Hạnh, Vinh), Nhóm Thức ăn (Oánh, Hương, Lê, Ánh), Nhóm Quản lý tài nguyên (Công, Hữu Dương), Nhóm Công nghệ môi trường (Huy, Thu Hà), Nhóm Quản lý đất (Việt Hà, Thu Hà), Khoa TNMT (Đinh Hồng Duyên, Hoàng Hiệp), Khoa KT&QL (Nguyễn Hữu Nhuần, Linh), Khoa KT&QTKD (Trần Quang Trung), TT giống vật nuôi CLC (Hà)',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Giáng Hương'],
                'preparers' => ['Ban KHCN'],
            ],
            [
                'title' => 'Nghe báo cáo kết quả đề án sinh viên NCKH và kế hoạch triển khai đề án CLB sinh viên, đề án nối vòng tay lớn',
                'description' => 'Ban Giám đốc (Nguyễn Công Tiệp), TTQHCH&HTSV (Kim Hương), Ban CTCT&CTSV (Khoa), Ban KHCN (Trần Hiệp), TTNCXS&ĐMST (Minh), Bí thư và các Phó Bí thư Đoàn TN',
                'start_time' => Carbon::create(2025, 7, 16, 8, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 16, 10, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Nguyễn Công Tiệp, Kim Hương, Khoa, Trần Hiệp, Minh, Bí thư và các Phó Bí thư Đoàn TN',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Giáng Hương'],
                'preparers' => ['Ban KHCN', 'Đoàn TN'],
            ],
            [
                'title' => 'Làm việc với đơn vị đối tác về công tác xuất bản',
                'description' => 'Nhà xuất bản Học viện NN (Lê Anh, Tuấn Anh), Đơn vị đối tác',
                'start_time' => Carbon::create(2025, 7, 16, 8, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 16, 10, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Vũ Ngọc Huyên',
                'participants' => 'Lê Anh, Tuấn Anh, Đơn vị đối tác',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Nhà xuất bản Học viện NN'],
                'preparers' => ['NXB Học viện NN'],
            ],
            [
                'title' => 'Nghiệm thu gói thầu: Cải tạo cơ sở vật chất giảng đường trung tâm',
                'description' => 'Ban Tài chính & Kế toán (Lãnh đạo Ban, Huyền), Ban ĐBCL&PC (Ước), Trung tâm dịch vụ trường học (Hải, Kim), Ban CSVC&ĐT (Nam, chuyên viên PT), Tư vấn giám sát, Tư vấn quản lý dự án, Nhà thầu thi công',
                'start_time' => Carbon::create(2025, 7, 16, 9, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 16, 11, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Phạm Văn Cường',
                'participants' => 'Huyền, Ước, Hải, Kim, Nam, chuyên viên PT, Tư vấn giám sát, Tư vấn quản lý dự án, Nhà thầu thi công',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Giảng trường trung tâm'],
                'preparers' => ['Ban CSVC và ĐT'],
            ],
            [
                'title' => 'Họp đề xuất Danh mục các dự án đầu tư công giai đoạn 2026-2030',
                'description' => 'Ban Giám đốc, Thường trực Hội đồng Học viện (Viên, Liết, Thâu), Đảng ủy viên, Trưởng các đơn vị: Ban Tài chính Kế toán, Văn phòng Học viện, Ban Khoa học Công nghệ, Ban Quản lý Đào tạo, Ban Cơ sở vật chất và Đầu tư',
                'start_time' => Carbon::create(2025, 7, 16, 10, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 16, 11, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Viên, Liết, Thâu, Đảng ủy viên, Trưởng các đơn vị: Ban TCKT, VPHV, Ban KHCN, Ban QLĐT, Ban CSVC&ĐT',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Giáng Hương'],
                'preparers' => ['Ban CSVC và ĐT'],
            ],
            [
                'title' => 'Làm việc với Quỹ Phát triển KHCN Quốc gia về nhiệm vụ "Nghiên cứu công nghệ thiết kế, chế tạo dây chuyền thiết bị sơ chế bảo quản cà rốt"',
                'description' => 'Mã số: ĐTĐL.CN-89/21, do PGS.TS. Lê Minh Lư làm chủ nhiệm. Thành phần: Ban KHCN, Ban TCKT, Khoa Cơ điện, Chủ nhiệm và Thành viên tham gia thực hiện đề tài',
                'start_time' => Carbon::create(2025, 7, 16, 14, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 16, 17, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Phạm Văn Cường',
                'participants' => 'Lê Minh Lư, Ban KHCN, Ban TCKT, Khoa Cơ điện, Thành viên tham gia thực hiện đề tài',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Bộ Khoa học và Công nghệ'],
                'preparers' => ['Ban KHCN'],
            ],
            [
                'title' => 'Nghiệm thu gói thầu: Thi công xây lắp đường dây cấp nguồn TBA giống lúa',
                'description' => 'Ban Tài chính & Kế toán (Lãnh đạo Ban, Huyền), Ban ĐBCL và Pháp chế (Ước), Ban CSVC&ĐT (Nam và chuyên viên phụ trách), Tư vấn giám sát, Nhà thầu thi công',
                'start_time' => Carbon::create(2025, 7, 16, 15, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 16, 16, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Công Tiệp',
                'participants' => 'Huyền, Ước, Nam, chuyên viên phụ trách, Tư vấn giám sát, Nhà thầu thi công',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Công trường thi công'],
                'preparers' => ['Ban CSVC và ĐT'],
            ],
            [
                'title' => 'Tham gia tiếp xúc cử tri sau kỳ họp thứ Chín, Quốc hội khóa XV',
                'description' => 'Đại biểu Quốc hội Nguyễn Thị Lan, Tổ công tác',
                'start_time' => Carbon::create(2025, 7, 17, 8, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 17, 11, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Nguyễn Thị Lan, Tổ công tác',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Trụ sở HĐND-UBND xã Thạch Thất'],
                'preparers' => ['Tổ công tác'],
            ],
            [
                'title' => 'Họp tiến độ công trình ao sen',
                'description' => 'Ban CSVC&ĐT (Nam và cán bộ chuyên môn), tổ giám sát độc lập (Ước, Huân), VPHV (Huân, Thuần), TVQLDA, TVGS, nhà thầu thi công',
                'start_time' => Carbon::create(2025, 7, 17, 9, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 17, 11, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Công Tiệp',
                'participants' => 'Nam, Ước, Huân, Thuần, TVQLDA, TVGS, nhà thầu thi công',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Bằng Lăng'],
                'preparers' => ['Ban CSVC và ĐT'],
            ],
            [
                'title' => 'Trình bày phương án thiết kế sân tập Golf',
                'description' => 'HĐKH&ĐT (Viên), HĐHV (Xuân Cường), Ban CSVC&ĐT, Văn phòng Học viện, TT GDTCTT',
                'start_time' => Carbon::create(2025, 7, 17, 14, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 17, 15, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Vũ Ngọc Huyên',
                'participants' => 'Viên, Xuân Cường, Ban CSVC&ĐT, VPHV, TT GDTCTT',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Giáng Hương'],
                'preparers' => ['Ban CSVC và ĐT'],
            ],
            [
                'title' => 'Họp nghe báo cáo tiến độ quảng bá tuyển sinh năm 2025',
                'description' => 'Ban Giám đốc, HĐKH&ĐT (Viên), Trưởng các ban chức năng, Phó Trưởng một số ban (Tùng, Tự, Lan Hương), Trưởng các khoa, viện, trung tâm, công ty, Bí thư và Phó Bí thư Đoàn TN',
                'start_time' => Carbon::create(2025, 7, 17, 15, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 17, 17, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Ban Giám đốc, Viên, Tùng, Tự, Lan Hương, Trưởng các khoa, viện, trung tâm, công ty, Bí thư và Phó Bí thư Đoàn TN',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Hội trường Nguyệt Quế'],
                'preparers' => ['TT QHCC&HTSV'],
            ],
            [
                'title' => 'Hội thảo triển khai Khung năng lực số cho sinh viên',
                'description' => 'Kinh nghiệm quốc tế và thực tiễn Việt Nam. Thành phần: Ban Giám đốc (Phạm Văn Cường), Ban QLĐT (Tự, Quốc, Tuyết), Ban ĐBCL và PC, Lãnh đạo khoa và trợ lý đào tạo, Quản trị mạng',
                'start_time' => Carbon::create(2025, 7, 18, 8, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 18, 12, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Bộ Giáo dục và Đào tạo',
                'participants' => 'Phạm Văn Cường, Tự, Quốc, Tuyết, Ban ĐBCL và PC, Lãnh đạo khoa và trợ lý đào tạo, Quản trị mạng',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Hội trường Nguyệt Quế'],
                'preparers' => ['Ban QLĐT'],
            ],
            [
                'title' => 'Thảo luận hợp tác với thành phố Tottori Nhật Bản',
                'description' => 'Đoàn thành phố Tottori Nhật Bản, TT CUNNL, trung tâm dịch vụ VNUA IDS',
                'start_time' => Carbon::create(2025, 7, 18, 10, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 18, 12, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Vũ Ngọc Huyên',
                'participants' => 'Đoàn thành phố Tottori Nhật Bản, TT CUNNL, VNUA IDS',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Anh Đào'],
                'preparers' => ['TT CUNNL'],
            ],
            [
                'title' => 'Họp tiến độ kiểm định 8 CTĐT đại học năm 2025',
                'description' => 'Trưởng các khoa (Chăn nuôi, DL&NN, KT&QTKD, KT&QL, TN&MT, Thủy sản), Trưởng nhóm viết BCTĐG, Thư ký hội đồng TĐG, Cán bộ phụ trách minh chứng, TT Tin học (Dũng), Tổ ĐBCL',
                'start_time' => Carbon::create(2025, 7, 18, 14, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 18, 15, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Phạm Văn Cường',
                'participants' => 'Trưởng các khoa (Chăn nuôi, DL&NN, KT&QTKD, KT&QL, TN&MT, Thủy sản), Trưởng nhóm viết BCTĐG, Thư ký hội đồng TĐG, Cán bộ phụ trách minh chứng, Dũng, Tổ ĐBCL',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Hội trường Nguyệt Quế'],
                'preparers' => ['Ban ĐBCL và Pháp chế'],
            ],
            [
                'title' => 'Nghiệm thu đề tài KHCN cấp Học viện trọng điểm',
                'description' => 'Do TS. Nguyễn Đình Thi làm chủ nhiệm. Thành viên Hội đồng, Ban KHCN',
                'start_time' => Carbon::create(2025, 7, 18, 14, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 18, 16, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Vũ Ngọc Huyên',
                'participants' => 'Nguyễn Đình Thi, Thành viên Hội đồng, Ban KHCN',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Hoa Sứ'],
                'preparers' => ['Ban KHCN'],
            ],
            [
                'title' => 'Họp triển khai đề án sinh viên nghiên cứu khoa học VNUA năm 2025',
                'description' => 'Ban Giám đốc, Trưởng các khoa, Trưởng các nhóm nghiên cứu mạnh, tinh hoa, xuất sắc, Ban KHCN, Ban QLĐT, Ban CTCT&CTSV, TT QHCC&HTSV, TT NCXS&ĐMST, Trợ lý khoa học các khoa, Ban Bí thư Đoàn TN, Văn phòng Đoàn TN',
                'start_time' => Carbon::create(2025, 7, 18, 15, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 18, 17, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Ban Giám đốc, Trưởng các khoa, Trưởng các nhóm nghiên cứu, Ban KHCN, Ban QLĐT, Ban CTCT&CTSV, TT QHCC&HTSV, TT NCXS&ĐMST, Trợ lý khoa học, Ban Bí thư Đoàn TN, Văn phòng Đoàn TN',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Hội trường Nguyệt Quế'],
                'preparers' => ['Đoàn TN'],
            ],
            [
                'title' => 'Họp rút kinh nghiệm tổ chức thi trên hệ thống phần mềm VNUA-TEST năm học 2024-2025',
                'description' => 'Đại diện Ban chủ nhiệm khoa và Bộ môn phụ trách học phần, Trưởng học phần của 13 Học phần chung, Ban QLĐT, Ban CSVC&ĐT, TT Tin học, Bộ phận Quản trị mạng',
                'start_time' => Carbon::create(2025, 7, 18, 15, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 18, 17, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Phạm Văn Cường',
                'participants' => 'Ban chủ nhiệm khoa, Bộ môn phụ trách học phần, Trưởng học phần, Ban QLĐT, Ban CSVC&ĐT, TT Tin học, Bộ phận Quản trị mạng',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Giáng Hương'],
                'preparers' => ['Ban ĐBCL và Pháp chế'],
            ],
            [
                'title' => 'Lễ kỷ niệm 249 năm Quốc khánh Hoa Kỳ và 30 năm thiết lập quan hệ ngoại giao Hoa Kỳ - Việt Nam',
                'description' => 'GĐ Nguyễn Thị Lan, Lãnh đạo Ban HTQT',
                'start_time' => Carbon::create(2025, 7, 18, 18, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 18, 20, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Nguyễn Thị Lan, Ban HTQT',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['KS JW Marirott'],
                'preparers' => ['Ban HTQT'],
            ],
            [
                'title' => 'Làm việc với Hội Tự động hoá Việt Nam về kế hoạch hợp tác đào tạo và nghiên cứu khoa học',
                'description' => 'GS.TS. Trần Đức Viên, Ban Giám đốc (Vũ Ngọc Huyên), Ban QLĐT (Hải), Ban KHCN (Trần Hiệp), Khoa Cơ Điện (Trường, Hiên, Học)',
                'start_time' => Carbon::create(2025, 7, 19, 15, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 19, 17, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Vũ Ngọc Huyên',
                'participants' => 'Trần Đức Viên, Vũ Ngọc Huyên, Hải, Trần Hiệp, Trường, Hiên, Học',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Giáng Hương'],
                'preparers' => ['Khoa Cơ Điện'],
            ],
            [
                'title' => 'Tiếp cán bộ, viên chức, người lao động và người học',
                'description' => 'Ban Thanh tra, Ban Thanh tra nhân dân',
                'start_time' => Carbon::create(2025, 7, 15, 8, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 15, 11, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Nguyễn Thị Lan',
                'participants' => 'Ban Thanh tra, Ban Thanh tra nhân dân',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng Tiếp dân (P123 - Tòa nhà Trung tâm)'],
                'preparers' => ['VPHV'],
            ],
            [
                'title' => 'Tiếp đoàn SFSI về dự án Cooperative Innovation Ecosystem Development',
                'description' => 'Thảo luận kế hoạch triển khai dự án. Thành phần: Ban HTQT (Nguyễn Việt Long, Dương Thị Minh Phượng), Ban KHCN (Trần Hiệp), Khoa KT&QL (Nguyễn Hữu Nhuần, Trần Thế Cường), Viện AMI (Ngô Sỹ Đạt), Nhóm NCM HTX (Trần Quang Trung), TT NCXS ĐMST (Trần Đức Minh), SFSI (Michael Murphy, Michael Barry, Aoife Roche, Hoàng Văn Tú)',
                'start_time' => Carbon::create(2025, 7, 14, 14, 0, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'end_time' => Carbon::create(2025, 7, 14, 16, 30, 0, 'Asia/Ho_Chi_Minh')->utc(),
                'host' => 'Trần Đức Viên',
                'participants' => 'Nguyễn Việt Long, Dương Thị Minh Phượng, Trần Hiệp, Nguyễn Hữu Nhuần, Trần Thế Cường, Ngô Sỹ Đạt, Trần Quang Trung, Trần Đức Minh, Michael Murphy, Michael Barry, Aoife Roche, Hoàng Văn Tú',
                'status' => 'approved',
                'creator_id' => $chanhvp->id,
                'locations' => ['Phòng họp Hoa Sứ'],
                'preparers' => ['Ban HTQT'],
            ],
        ];

        foreach ($events as $eventData) {
            $eventLocations = $eventData['locations'];
            $preparers = $eventData['preparers'];
            unset($eventData['locations'], $eventData['preparers']);

            // Create event
            $event = Event::create($eventData);

            // Attach locations
            foreach ($eventLocations as $locationName) {
                if (isset($locations[$locationName])) {
                    $event->locations()->attach($locations[$locationName]->id);
                } else {
                    throw new \Exception("Location not found: {$locationName}");
                }
            }

            // Attach preparer departments
            foreach ($preparers as $departmentName) {
                if (isset($departments[$departmentName])) {
                    $event->preparers()->attach($departments[$departmentName]->id);
                } else {
                    throw new \Exception("Department not found: {$departmentName}");
                }
            }
        }
    }
}
