<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Department;
use App\Models\Faculty;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        // Create or reference departments
        $departments = [
            'Khoa CNTT' => Department::firstOrCreate(['name' => 'Khoa CNTT'], ['id' => 1]),
            'Ban CSVC và ĐT' => Department::firstOrCreate(['name' => 'Ban CSVC và ĐT']),
            'VPĐU' => Department::firstOrCreate(['name' => 'VPĐU']),
            'Tổ công tác' => Department::firstOrCreate(['name' => 'Tổ công tác']),
            'Ban KHCN' => Department::firstOrCreate(['name' => 'Ban KHCN']),
            'TT QHCC&HTSV' => Department::firstOrCreate(['name' => 'TT QHCC&HTSV']),
            'NXB Học viện NN' => Department::firstOrCreate(['name' => 'NXB Học viện NN']),
            'Ban TCKT' => Department::firstOrCreate(['name' => 'Ban TCKT']),
            'Đoàn TN' => Department::firstOrCreate(['name' => 'Đoàn TN']),
            'Khoa TNMT' => Department::firstOrCreate(['name' => 'Khoa TNMT']),
            'Khoa Cơ Điện' => Department::firstOrCreate(['name' => 'Khoa Cơ Điện']),
            'Ban ĐBCL và Pháp chế' => Department::firstOrCreate(['name' => 'Ban ĐBCL và Pháp chế']),
            'Ban HTQT' => Department::firstOrCreate(['name' => 'Ban HTQT']),
            'TT GDTCTT' => Department::firstOrCreate(['name' => 'TT GDTCTT']),
            'TT NCXS&ĐMST' => Department::firstOrCreate(['name' => 'TT NCXS&ĐMST']),
            'Ban QLĐT' => Department::firstOrCreate(['name' => 'Ban QLĐT']),
            'Ban CTCT&CTSV' => Department::firstOrCreate(['name' => 'Ban CTCT&CTSV']),
            'VPHV' => Department::firstOrCreate(['name' => 'VPHV']),
            'TT CUNNL' => Department::firstOrCreate(['name' => 'TT CUNNL']),
            'Viện AMI' => Department::firstOrCreate(['name' => 'Viện AMI']),
            'Khoa KT&QL' => Department::firstOrCreate(['name' => 'Khoa KT&QL']),
            'Khoa DL&NN' => Department::firstOrCreate(['name' => 'Khoa DL&NN']),
            'Khoa KT&QTKD' => Department::firstOrCreate(['name' => 'Khoa KT&QTKD']),
            'Khoa Thủy sản' => Department::firstOrCreate(['name' => 'Khoa Thủy sản']),
            'TT Tin học' => Department::firstOrCreate(['name' => 'TT Tin học']),
            'Khoa Chăn nuôi' => Department::firstOrCreate(['name' => 'Khoa Chăn nuôi']),
            'Khoa Kinh tế' => Department::firstOrCreate(['name' => 'Khoa Kinh tế']),
            'Khoa KT&QLNN' => Department::firstOrCreate(['name' => 'Khoa KT&QLNN']),
            'Khoa Kinh tế và PTNT' => Department::firstOrCreate(['name' => 'Khoa Kinh tế và PTNT']),
            'Khoa Thú y' => Department::firstOrCreate(['name' => 'Khoa Thú y']),
            'TT giống vật nuôi CLC' => Department::firstOrCreate(['name' => 'TT giống vật nuôi CLC']),
        ];

        // Create or reference faculties
        // $faculties = [
        //     'Khoa TNMT' => Faculty::firstOrCreate(['name' => 'Khoa TNMT'], ['id' => 1]),
        //     'Khoa Cơ Điện' => Faculty::firstOrCreate(['name' => 'Khoa Cơ Điện']),
        //     'Khoa KT&QL' => Faculty::firstOrCreate(['name' => 'Khoa KT&QL']),
        //     'Khoa DL&NN' => Faculty::firstOrCreate(['name' => 'Khoa DL&NN']),
        //     'Khoa KT&QTKD' => Faculty::firstOrCreate(['name' => 'Khoa KT&QTKD']),
        //     'Khoa Thủy sản' => Faculty::firstOrCreate(['name' => 'Khoa Thủy sản']),
        // ];

        // Define users from Word document and RolePermissionTableSeeder
        $users = [
            [
                'sso_id' => 1,
                'user_name' => 'nguyenthilan',
                'first_name' => 'Lan',
                'last_name' => 'Nguyễn Thị',
                'email' => 'nguyenthilan@vnua.edu.vn',
                'role_sso' => 'chief_of_office',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA001',
                'primary_department_id' => null,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'chief_of_office',
            ],
            [
                'sso_id' => 2,
                'user_name' => 'nguyencongtiep',
                'first_name' => 'Tiệp',
                'last_name' => 'Nguyễn Công',
                'email' => 'nguyencongtiep@vnua.edu.vn',
                'role_sso' => 'chief_of_office',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA002',
                'primary_department_id' => $departments['Ban CSVC và ĐT']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'chief_of_office',
            ],
            [
                'sso_id' => 3,
                'user_name' => 'vungochuyen',
                'first_name' => 'Huyên',
                'last_name' => 'Vũ Ngọc',
                'email' => 'vungochuyen@vnua.edu.vn',
                'role_sso' => 'chief_of_office',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA003',
                'primary_department_id' => null,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'chief_of_office',
            ],
            [
                'sso_id' => 4,
                'user_name' => 'phamvancuong',
                'first_name' => 'Cường',
                'last_name' => 'Phạm Văn',
                'email' => 'phamvancuong@vnua.edu.vn',
                'role_sso' => 'chief_of_office',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA004',
                'primary_department_id' => null,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'chief_of_office',
            ],
            [
                'sso_id' => 5,
                'user_name' => 'vanthuhv',
                'first_name' => 'Thị',
                'last_name' => 'Trần',
                'email' => 'vanthuhv@vnua.edu.vn',
                'role_sso' => 'institute_secretary',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VTHV001',
                'primary_department_id' => $departments['VPĐU']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'institute_secretary',
            ],
            [
                'sso_id' => 6,
                'user_name' => 'vanthucntt',
                'first_name' => 'Hồng',
                'last_name' => 'Lê',
                'email' => 'vanthucntt@vnua.edu.vn',
                'role_sso' => 'department_secretary',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VTCNTT001',
                'primary_department_id' => $departments['Khoa CNTT']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'department_secretary',
            ],
            [
                'sso_id' => 7,
                'user_name' => 'cbvc',
                'first_name' => 'Minh',
                'last_name' => 'Phạm',
                'email' => 'cbvc@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'CBVC001',
                'primary_department_id' => null,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 432,
                'user_name' => 'tranducvien',
                'first_name' => 'Viên',
                'last_name' => 'Trần Đức',
                'email' => 'tranducvien@vnua.edu.vn',
                'role_sso' => 'chief_of_office',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA005',
                'primary_department_id' => null,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'chief_of_office',
            ],
            [
                'sso_id' => 234,
                'user_name' => 'leminhlu',
                'first_name' => 'Lư',
                'last_name' => 'Lê Minh',
                'email' => 'leminhlu@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA006',
                'primary_department_id' => $departments['Khoa Cơ Điện']->id,
                // 'faculty_id' => $faculties['Khoa Cơ Điện']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 2345,
                'user_name' => 'nguyendinhthi',
                'first_name' => 'Thi',
                'last_name' => 'Nguyễn Đình',
                'email' => 'nguyendinhthi@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA007',
                'primary_department_id' => $departments['Ban KHCN']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 231,
                'user_name' => 'tranhiep',
                'first_name' => 'Hiệp',
                'last_name' => 'Trần',
                'email' => 'tranhiep@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA008',
                'primary_department_id' => $departments['Ban KHCN']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 2311,
                'user_name' => 'dinhvandung',
                'first_name' => 'Dũng',
                'last_name' => 'Đinh Văn',
                'email' => 'dinhvandung@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA009',
                'primary_department_id' => $departments['Ban KHCN']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 4325,
                'user_name' => 'nguyenminhhan',
                'first_name' => 'Hân',
                'last_name' => 'Nguyễn Minh',
                'email' => 'nguyenminhhan@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA010',
                'primary_department_id' => $departments['Ban KHCN']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 4325561,
                'user_name' => 'tranquangtrung',
                'first_name' => 'Trung',
                'last_name' => 'Trần Quang',
                'email' => 'tranquangtrung@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA011',
                'primary_department_id' => $departments['Ban TCKT']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 321,
                'user_name' => 'nguyenvanquan',
                'first_name' => 'Quân',
                'last_name' => 'Nguyễn Văn',
                'email' => 'nguyenvanquan@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA012',
                'primary_department_id' => $departments['Ban CSVC và ĐT']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 532,
                'user_name' => 'nguyenvietlong',
                'first_name' => 'Long',
                'last_name' => 'Nguyễn Việt',
                'email' => 'nguyenvietlong@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA013',
                'primary_department_id' => $departments['Ban HTQT']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 253,
                'user_name' => 'kimhuong',
                'first_name' => 'Hương',
                'last_name' => 'Kim',
                'email' => 'kimhuong@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA014',
                'primary_department_id' => $departments['TT QHCC&HTSV']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 253634,
                'user_name' => 'khoa',
                'first_name' => 'Khoa',
                'last_name' => '',
                'email' => 'khoa@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA015',
                'primary_department_id' => $departments['Ban CTCT&CTSV']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 123412,
                'user_name' => 'minh',
                'first_name' => 'Minh',
                'last_name' => 'Trần Đức',
                'email' => 'minh@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA016',
                'primary_department_id' => $departments['TT NCXS&ĐMST']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1231231,
                'user_name' => 'leanh',
                'first_name' => 'Anh',
                'last_name' => 'Lê',
                'email' => 'leanh@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA017',
                'primary_department_id' => $departments['NXB Học viện NN']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 123543,
                'user_name' => 'tuananh',
                'first_name' => 'Anh',
                'last_name' => 'Tuấn',
                'email' => 'tuananh@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA018',
                'primary_department_id' => $departments['NXB Học viện NN']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 121234123,
                'user_name' => 'huyen',
                'first_name' => 'Huyền',
                'last_name' => '',
                'email' => 'huyen@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA019',
                'primary_department_id' => $departments['Ban TCKT']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 12543643,
                'user_name' => 'uoc',
                'first_name' => 'Ước',
                'last_name' => '',
                'email' => 'uoc@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA020',
                'primary_department_id' => $departments['Ban ĐBCL và Pháp chế']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 17475432,
                'user_name' => 'hai',
                'first_name' => 'Hải',
                'last_name' => '',
                'email' => 'hai@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA021',
                'primary_department_id' => $departments['TT QHCC&HTSV']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 10392,
                'user_name' => 'kim',
                'first_name' => 'Kim',
                'last_name' => '',
                'email' => 'kim@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA022',
                'primary_department_id' => $departments['TT QHCC&HTSV']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039223523,
                'user_name' => 'nam',
                'first_name' => 'Nam',
                'last_name' => '',
                'email' => 'nam@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA023',
                'primary_department_id' => $departments['Ban CSVC và ĐT']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 103924155137148857,
                'user_name' => 'trantrongphuong',
                'first_name' => 'Phương',
                'last_name' => 'Trần Trọng',
                'email' => 'trantrongphuong@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA024',
                'primary_department_id' => $departments['Khoa TNMT']->id,
                // 'faculty_id' => $faculties['Khoa TNMT']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 10392897159871985,
                'user_name' => 'xuancuong',
                'first_name' => 'Cường',
                'last_name' => 'Xuân',
                'email' => 'xuancuong@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA025',
                'primary_department_id' => $departments['TT GDTCTT']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 103924189715987198,
                'user_name' => 'tung',
                'first_name' => 'Tùng',
                'last_name' => '',
                'email' => 'tung@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA026',
                'primary_department_id' => $departments['Ban KHCN']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 10392415719,
                'user_name' => 'tu',
                'first_name' => 'Tự',
                'last_name' => '',
                'email' => 'tu@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA027',
                'primary_department_id' => $departments['Ban QLĐT']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 103929871,
                'user_name' => 'lanhuong',
                'first_name' => 'Hương',
                'last_name' => 'Lan',
                'email' => 'lanhuong@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA028',
                'primary_department_id' => $departments['TT QHCC&HTSV']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039241551387,
                'user_name' => 'nguyenhuunhuan',
                'first_name' => 'Nhuần',
                'last_name' => 'Nguyễn Hữu',
                'email' => 'nguyenhuunhuan@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA029',
                'primary_department_id' => $departments['Khoa KT&QL']->id,
                // 'faculty_id' => $faculties['Khoa KT&QL']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039241598,
                'user_name' => 'tranthecuong',
                'first_name' => 'Cường',
                'last_name' => 'Trần Thế',
                'email' => 'tranthecuong@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA030',
                'primary_department_id' => $departments['Khoa KT&QL']->id,
                // 'faculty_id' => $faculties['Khoa KT&QL']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039241597159,
                'user_name' => 'ngosydat',
                'first_name' => 'Đạt',
                'last_name' => 'Ngô Sỹ',
                'email' => 'ngosydat@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA031',
                'primary_department_id' => $departments['Viện AMI']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039241551371489715,
                'user_name' => 'phan',
                'first_name' => 'Phan',
                'last_name' => '',
                'email' => 'phan@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA032',
                'primary_department_id' => $departments['Khoa Chăn nuôi']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 103924155137148971,
                'user_name' => 'hoa',
                'first_name' => 'Hoa',
                'last_name' => '',
                'email' => 'hoa@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA033',
                'primary_department_id' => $departments['Khoa Chăn nuôi']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 10392415513714897,
                'user_name' => 'lam',
                'first_name' => 'Lâm',
                'last_name' => '',
                'email' => 'lam@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA034',
                'primary_department_id' => $departments['Khoa Chăn nuôi']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039241551371489,
                'user_name' => 'huuanh',
                'first_name' => 'Anh',
                'last_name' => 'Hữu',
                'email' => 'huuanh@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA035',
                'primary_department_id' => $departments['Khoa Thú y']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 103924155137148,
                'user_name' => 'ngan',
                'first_name' => 'Ngân',
                'last_name' => '',
                'email' => 'ngan@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA036',
                'primary_department_id' => $departments['Khoa Thú y']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 10392415513714,
                'user_name' => 'giap',
                'first_name' => 'Giáp',
                'last_name' => '',
                'email' => 'giap@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA037',
                'primary_department_id' => $departments['Khoa Thú y']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039241551371,
                'user_name' => 'ha',
                'first_name' => 'Hà',
                'last_name' => '',
                'email' => 'ha@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA038',
                'primary_department_id' => $departments['Khoa Thú y']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 103924155137,
                'user_name' => 'chien',
                'first_name' => 'Chiên',
                'last_name' => '',
                'email' => 'chien@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA039',
                'primary_department_id' => $departments['Khoa Thú y']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 10392415513,
                'user_name' => 'duc',
                'first_name' => 'Đức',
                'last_name' => '',
                'email' => 'duc@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA040',
                'primary_department_id' => $departments['Khoa Thú y']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039241551,
                'user_name' => 'thuha',
                'first_name' => 'Hà',
                'last_name' => 'Thu',
                'email' => 'thuha@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA041',
                'primary_department_id' => $departments['Khoa Thú y']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 103924155,
                'user_name' => 'hoai',
                'first_name' => 'Hoài',
                'last_name' => '',
                'email' => 'hoai@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA042',
                'primary_department_id' => $departments['Khoa Thủy sản']->id,
                // 'faculty_id' => $faculties['Khoa Thủy sản']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 10392415,
                'user_name' => 'manh',
                'first_name' => 'Mạnh',
                'last_name' => '',
                'email' => 'manh@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA043',
                'primary_department_id' => $departments['Khoa Thủy sản']->id,
                // 'faculty_id' => $faculties['Khoa Thủy sản']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039241,
                'user_name' => 'van',
                'first_name' => 'Vạn',
                'last_name' => '',
                'email' => 'van@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA044',
                'primary_department_id' => $departments['Khoa Thủy sản']->id,
                // 'faculty_id' => $faculties['Khoa Thủy sản']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 103924,
                'user_name' => 'thu',
                'first_name' => 'Thu',
                'last_name' => '',
                'email' => 'thu@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA045',
                'primary_department_id' => $departments['Khoa Thủy sản']->id,
                // 'faculty_id' => $faculties['Khoa Thủy sản']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 10392102471202682,
                'user_name' => 'tung2',
                'first_name' => 'Tùng',
                'last_name' => '',
                'email' => 'tung2@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA046',
                'primary_department_id' => $departments['Khoa Thủy sản']->id,
                // 'faculty_id' => $faculties['Khoa Thủy sản']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1031204612641268471,
                'user_name' => 'hanh',
                'first_name' => 'Hạnh',
                'last_name' => '',
                'email' => 'hanh@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA047',
                'primary_department_id' => $departments['Khoa Chăn nuôi']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039210247120461247,
                'user_name' => 'vinh',
                'first_name' => 'Vinh',
                'last_name' => '',
                'email' => 'vinh@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA048',
                'primary_department_id' => $departments['Khoa Chăn nuôi']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039212684,
                'user_name' => 'oanh',
                'first_name' => 'Oánh',
                'last_name' => '',
                'email' => 'oanh@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA049',
                'primary_department_id' => $departments['Khoa Chăn nuôi']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039210247120268,
                'user_name' => 'huong',
                'first_name' => 'Hương',
                'last_name' => '',
                'email' => 'huong@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA050',
                'primary_department_id' => $departments['Khoa Chăn nuôi']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1120461264126,
                'user_name' => 'le',
                'first_name' => 'Lê',
                'last_name' => '',
                'email' => 'le@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA051',
                'primary_department_id' => $departments['Khoa Chăn nuôi']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039210247126412,
                'user_name' => 'anh',
                'first_name' => 'Ánh',
                'last_name' => '',
                'email' => 'anh@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA052',
                'primary_department_id' => $departments['Khoa Chăn nuôi']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 10391204612641,
                'user_name' => 'cong',
                'first_name' => 'Công',
                'last_name' => '',
                'email' => 'cong@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA053',
                'primary_department_id' => $departments['Khoa TNMT']->id,
                // 'faculty_id' => $faculties['Khoa TNMT']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039210247120461264,
                'user_name' => 'huuduong',
                'first_name' => 'Dương',
                'last_name' => 'Hữu',
                'email' => 'huuduong@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA054',
                'primary_department_id' => $departments['Khoa TNMT']->id,
                // 'faculty_id' => $faculties['Khoa TNMT']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 103921024712046126,
                'user_name' => 'huy',
                'first_name' => 'Huy',
                'last_name' => '',
                'email' => 'huy@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA055',
                'primary_department_id' => $departments['Khoa TNMT']->id,
                // 'faculty_id' => $faculties['Khoa TNMT']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 10392102471204612,
                'user_name' => 'vietha',
                'first_name' => 'Hà',
                'last_name' => 'Việt',
                'email' => 'vietha@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA056',
                'primary_department_id' => $departments['Khoa TNMT']->id,
                // 'faculty_id' => $faculties['Khoa TNMT']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039210247120461,
                'user_name' => 'dinhhongduyen',
                'first_name' => 'Duyên',
                'last_name' => 'Đinh Hồng',
                'email' => 'dinhhongduyen@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA057',
                'primary_department_id' => $departments['Khoa TNMT']->id,
                // 'faculty_id' => $faculties['Khoa TNMT']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 103921024712046,
                'user_name' => 'hoanghiep',
                'first_name' => 'Hiệp',
                'last_name' => 'Hoàng',
                'email' => 'hoanghiep@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA058',
                'primary_department_id' => $departments['Khoa TNMT']->id,
                // 'faculty_id' => $faculties['Khoa TNMT']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 10392102471204,
                'user_name' => 'linh',
                'first_name' => 'Linh',
                'last_name' => '',
                'email' => 'linh@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA059',
                'primary_department_id' => $departments['Khoa KT&QL']->id,
                // 'faculty_id' => $faculties['Khoa KT&QL']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039210247120,
                'user_name' => 'ha2',
                'first_name' => 'Hà',
                'last_name' => '',
                'email' => 'ha2@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA060',
                'primary_department_id' => $departments['TT giống vật nuôi CLC']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 103921024712,
                'user_name' => 'quet',
                'first_name' => 'Quết',
                'last_name' => '',
                'email' => 'quet@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA061',
                'primary_department_id' => $departments['Ban QLĐT']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 10392102471,
                'user_name' => 'tuyet',
                'first_name' => 'Tuyết',
                'last_name' => '',
                'email' => 'tuyet@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA062',
                'primary_department_id' => $departments['Ban QLĐT']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1032471983249723641,
                'user_name' => 'huan',
                'first_name' => 'Huân',
                'last_name' => '',
                'email' => 'huan@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA063',
                'primary_department_id' => $departments['VPHV']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 103921024324972364,
                'user_name' => 'thuan',
                'first_name' => 'Thuần',
                'last_name' => '',
                'email' => 'thuan@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA064',
                'primary_department_id' => $departments['VPHV']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1034719832497236,
                'user_name' => 'truong',
                'first_name' => 'Trường',
                'last_name' => '',
                'email' => 'truong@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA065',
                'primary_department_id' => $departments['Khoa Cơ Điện']->id,
                // 'faculty_id' => $faculties['Khoa Cơ Điện']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 10392102723,
                'user_name' => 'hien',
                'first_name' => 'Hiên',
                'last_name' => '',
                'email' => 'hien@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA066',
                'primary_department_id' => $departments['Khoa Cơ Điện']->id,
                // 'faculty_id' => $faculties['Khoa Cơ Điện']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039210247198324972,
                'user_name' => 'hoc',
                'first_name' => 'Học',
                'last_name' => '',
                'email' => 'hoc@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA067',
                'primary_department_id' => $departments['Khoa Cơ Điện']->id,
                // 'faculty_id' => $faculties['Khoa Cơ Điện']->id,
                'protected' => true,
                'role' => 'staff',
            ],
            [
                'sso_id' => 1039210247198324,
                'user_name' => 'duongthiminhphuong',
                'first_name' => 'Phương',
                'last_name' => 'Dương Thị Minh',
                'email' => 'duongthiminhphuong@vnua.edu.vn',
                'role_sso' => 'staff',
                'status' => 'active',
                'phone' => '091277893',
                'code' => 'VNUA068',
                'primary_department_id' => $departments['Ban HTQT']->id,
                // 'faculty_id' => null,
                'protected' => true,
                'role' => 'staff',
            ],
        ];

        // Create users and assign roles
        foreach ($users as $userData) {
            $role = $userData['role'];
            unset($userData['role']);
            $user = User::create($userData);
            $user->assignRole($role);
        }
    }
}
